### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/Documentation#126]
## To reproduce

1. go to https://docs.mistyrobotics.com/misty-ii/reference/javascript-api/
2. try to follow link to "JavaScript SDK Architecture" in the left navigation bar

## Proposed solution

the link is currently <https://docs.mistyrobotics.com/misty-ii/coding-misty/javascript-sdk-architecture>, but it should be https://docs.mistyrobotics.com/misty-ii/javascript-sdk/javascript-skill-architecture/

**Comment by johnathanDOS** [comment]
Thanks @slivingston, I'll look into this today. It appears there's more going on than just a broken link; the page at https://docs.mistyrobotics.com/misty-ii/reference/javascript-api/ shouldn't actually exist anymore, and that URL should instead redirect to https://docs.mistyrobotics.com/misty-ii/javascript-sdk/api-reference/. It's possible there was a mistake in the redirect routing.

**Comment by johnathanDOS** [comment]
After digging in, the root of this problem seems to be that the redirect from https://docs.mistyrobotics.com/misty-ii/reference/javascript-api/ wasn't set up correctly. I've made a few changes and pushed them to the production site.

The resource at https://docs.mistyrobotics.com/misty-ii/reference/javascript-api/ may still be cached in your browser. Try opening https://docs.mistyrobotics.com/misty-ii/reference/javascript-api/ and doing a hard refresh to see if you are redirected to the new location for the page at https://docs.mistyrobotics.com/misty-ii/javascript-sdk/api-reference/.
